language: android
android:
  components:
    - build-tools-19.1.0
    - extra-android-support
    - extra-android-m2repository
    - android-19
  licenses:
    - '.+'
script: "./gradlew build"

env:
  global:
    secure: "KfZwFDjIeOGN7AGP6G/9d8S/F5j02yK1/s08LUBjGMi5P/tYkf5tp06DWVaQBB/EBFAFrCkPif2tcwAJYwpznz4fwMuGmSjBLFRiVXe92lhgvwb3BSbHaa7Lwuqi/7GTGQxQ4KgZofP4cEcaLR72V7ZnB1CDcHsmhgfOsJRlw7o="

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: "app/build/outputs/aar/app.aar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true